"""lingopal URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index,name="index"),
    path('register' , register_attempt , name="register_attempt"),
    path('logout' , logout_attempt , name="logout_attempt"),
    path('login' , login_attempt , name="login_attempt"),
    path('success' , success_attempt , name='success_attempt'),
    path('feedback' , feedback_attempt , name='feedback_attempt'),
    path('home' , home_attempt , name='home_attempt'),
    path('matches' , matches_attempt , name='matches_attempt'),
    path('profile' , profile_attempt , name='profile_attempt'),
    path('user_language' , user_language , name='user_language'),
     path('language_test' , language_test , name='language_test'),
    path('update_profile' , update_profile , name='update_profile'),
    path('quiz' , quiz_attempt , name='quiz_attempt'),
    path('quiz_beginner_arabic' , quiz_beginner_arabic , name='quiz_beginner_arabic'),
    path('quiz_intermediate_arabic' , quiz_intermediate_arabic , name='quiz_intermediate_arabic'),
    path('quiz_advanced_arabic' , quiz_advanced_arabic , name='quiz_advanced_arabic'),
    path('quiz_beginner_bengali' , quiz_beginner_bengali , name='quiz_beginner_bengali'),
    path('quiz_intermediate_bengali' , quiz_intermediate_bengali , name='quiz_intermediate_bengali'),
    path('quiz_advanced_bengali' , quiz_advanced_bengali , name='quiz_advanced_bengali'),
    path('quiz_beginner_chinese' , quiz_beginner_chinese , name='quiz_beginner_chinese'),
    path('quiz_intermediate_chinese' , quiz_intermediate_chinese , name='quiz_intermediate_chinese'),
    path('quiz_advanced_chinese' , quiz_advanced_chinese , name='quiz_advanced_chinese'),
    path('quiz_beginner_dutch' , quiz_beginner_dutch , name='quiz_beginner_dutch'),
    path('quiz_intermediate_dutch' , quiz_intermediate_dutch , name='quiz_intermediate_dutch'),
    path('quiz_advanced_dutch' , quiz_advanced_dutch , name='quiz_advanced_dutch'),
    path('quiz_beginner_english' , quiz_beginner_english , name='quiz_beginner_english'),
    path('quiz_intermediate_english' , quiz_intermediate_english , name='quiz_intermediate_english'),
    path('quiz_advanced_english' , quiz_advanced_english , name='quiz_advanced_english'),
    path('quiz_beginner_french' , quiz_beginner_french , name='quiz_beginner_french'),
    path('quiz_intermediate_french' , quiz_intermediate_french , name='quiz_intermediate_french'),
    path('quiz_advanced_french' , quiz_advanced_french , name='quiz_advanced_french'),
    path('quiz_beginner_german' , quiz_beginner_german , name='quiz_beginner_german'),
    path('quiz_intermediate_german' , quiz_intermediate_german , name='quiz_intermediate_german'),
    path('quiz_advanced_german' , quiz_advanced_german , name='quiz_advanced_german'),
    path('quiz_beginner_greek' , quiz_beginner_greek , name='quiz_beginner_greek'),
    path('quiz_intermediate_greek' , quiz_intermediate_greek , name='quiz_intermediate_greek'),
    path('quiz_advanced_greek' , quiz_advanced_greek , name='quiz_advanced_greek'),
    path('quiz_beginner_gujarati' , quiz_beginner_gujarati , name='quiz_beginner_gujarati'),
    path('quiz_intermediate_gujarati' , quiz_intermediate_gujarati , name='quiz_intermediate_gujarati'),
    path('quiz_advanced_gujarati' , quiz_advanced_gujarati , name='quiz_advanced_gujarati'),
    path('quiz_beginner_spanish' , quiz_beginner_spanish , name='quiz_beginner_spanish'),
    path('quiz_intermediate_spanish' , quiz_intermediate_spanish , name='quiz_intermediate_spanish'),
    path('quiz_advanced_spanish' , quiz_advanced_spanish , name='quiz_advanced_spanish'),
    path('quiz_beginner_hindi' , quiz_beginner_hindi , name='quiz_beginner_hindi'),
    path('quiz_intermediate_hindi' , quiz_intermediate_hindi , name='quiz_intermediate_hindi'),
    path('quiz_advanced_hindi' , quiz_advanced_hindi , name='quiz_advanced_hindi'),
    path('quiz_beginner_italian' , quiz_beginner_italian , name='quiz_beginner_italian'),
    path('quiz_intermediate_italian' , quiz_intermediate_italian , name='quiz_intermediate_italian'),
    path('quiz_advanced_italian' , quiz_advanced_italian , name='quiz_advanced_italian'),
    path('quiz_beginner_japanese' , quiz_beginner_japanese , name='quiz_beginner_japanese'),
    path('quiz_intermediate_japanese' , quiz_intermediate_japanese , name='quiz_intermediate_japanese'),
    path('quiz_advanced_japanese' , quiz_advanced_japanese , name='quiz_advanced_japanese'),
    path('quiz_beginner_korean' , quiz_beginner_korean , name='quiz_beginner_korean'),
    path('quiz_intermediate_korean' , quiz_intermediate_korean , name='quiz_intermediate_korean'),
    path('quiz_advanced_korean' , quiz_advanced_korean , name='quiz_advanced_korean'),
    path('quiz_beginner_odia' , quiz_beginner_odia , name='quiz_beginner_odia'),
    path('quiz_intermediate_odia' , quiz_intermediate_odia , name='quiz_intermediate_odia'),
    path('quiz_advanced_odia' , quiz_advanced_odia , name='quiz_advanced_odia'),
    path('quiz_beginner_punjabi' , quiz_beginner_punjabi , name='quiz_beginner_punjabi'),
    path('quiz_intermediate_punjabi' , quiz_intermediate_punjabi , name='quiz_intermediate_punjabi'),
    path('quiz_advanced_punjabi' , quiz_advanced_punjabi , name='quiz_advanced_punjabi'),
    path('quiz_beginner_russian' , quiz_beginner_russian , name='quiz_beginner_russian'),
    path('quiz_intermediate_russian' , quiz_intermediate_russian , name='quiz_intermediate_russian'),
    path('quiz_advanced_russian' , quiz_advanced_russian , name='quiz_advanced_russian'),
    path('quiz_beginner_tamil' , quiz_beginner_tamil , name='quiz_beginner_tamil'),
    path('quiz_intermediate_tamil' , quiz_intermediate_tamil , name='quiz_intermediate_tamil'),
    path('quiz_advanced_tamil' , quiz_advanced_tamil , name='quiz_advanced_tamil'),
    path('quiz_beginner_telugu' , quiz_beginner_telugu , name='quiz_beginner_telugu'),
    path('quiz_intermediate_telugu' , quiz_intermediate_telugu , name='quiz_intermediate_telugu'),
    path('quiz_advanced_telugu' , quiz_advanced_telugu , name='quiz_advanced_telugu'),
    path('quiz_beginner_urdu' , quiz_beginner_urdu , name='quiz_beginner_urdu'),
    path('quiz_intermediate_urdu' , quiz_intermediate_urdu , name='quiz_intermediate_urdu'),
    path('quiz_advanced_urdu' , quiz_advanced_urdu , name='quiz_advanced_urdu'),
    path('resources' , resources_attempt , name='resources_attempt'),
    path('settings' , settings_attempt , name='settings_attempt'),
    path('teacher_profile' , teacher_profile_attempt , name='teacher_profile_attempt'),
    path('playlist' , playlist_attempt , name='playlist_attempt'),
    path('playlist_arabic' , playlist_arabic , name='playlist_arabic'),
    path('playlist_bengali' , playlist_bengali , name='playlist_bengali'),
    path('playlist_chinese' , playlist_chinese , name='playlist_chinese'),
    path('playlist_dutch' , playlist_dutch , name='playlist_dutch'),
    path('playlist_english' , playlist_english , name='playlist_english'),
    path('playlist_french' , playlist_french , name='playlist_french'),
    path('playlist_german' , playlist_german , name='playlist_german'),
    path('playlist_greek' , playlist_greek , name='playlist_greek'),
    path('playlist_gujarati' , playlist_gujarati , name='playlist_gujarati'),
    path('playlist_hindi' , playlist_hindi , name='playlist_hindi'),
    path('playlist_italian' , playlist_italian , name='playlist_italian'),
    path('playlist_japanese' , playlist_japanese , name='playlist_japanese'),
    path('playlist_tamil' , playlist_tamil , name='playlist_tamil'),
    path('playlist_korean' , playlist_korean , name='playlist_korean'),
    path('playlist_odia' , playlist_odia , name='playlist_odia'),
    path('playlist_punjabi' , playlist_punjabi , name='playlist_punjabi'),
    path('playlist_russian' , playlist_russian , name='playlist_russian'),
    path('playlist_spanish' , playlist_spanish , name='playlist_spanish'),
    path('playlist_telugu' , playlist_telugu , name='playlist_telugu'),
    path('playlist_urdu' , playlist_urdu , name='playlist_urdu'),
    path('verify' , verify_attempt , name='verify_attempt'),
    path('verifyEmail' , VerifyOTP , name='verifyEmail'),
    path('verifyForgot' , VerifyForgot , name='verifyForgot'),
    path('take_test/<str:language>' , take_test , name='take_test'),
    path('result_update' , result_update , name='result_update'),
    path('chatroom' , chatroom , name='room_attempt'),
    path('<str:room>/' , room , name='room'),
    path('checkview' , checkview , name='checkview'),
    path('send' , send , name='send'),
    path('getMessages/<str:room>/' , getMessages , name='getMessages'),
    path('dashboard' , dashboard , name='dashboard'),
    path('meeting' , videocall , name='meeting'),
    path('join' , join_room , name='join'),
    path('forgot_password' , forgot_password , name='forgot_password'),
    path('verify_forgot' , verify_forgot , name='verify_forgot'),
    path('update_password' , update_password , name='update_password'),
    path('success_forgot' , success_forgot , name='success_forgot'),
    path('send_request', send_request, name='send_request'),
    path('accept_request', accept_request, name='accept_request'),
    path('decline_request', decline_request, name='decline_request'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

